#!/usr/bin/env node
/**
 * Static site generator.
 *
 * Produces `build/` — the exact tree Wrangler uploads. Rendering goes through
 * `src/render.js`, the same module the Express server uses, so the two outputs
 * cannot diverge.
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { content } = require('../src/config.js');
const { buildClientConfig, renderIndexHtml } = require('../src/render.js');
const { staticSecurityHeaders } = require('../src/security.js');

const ROOT = path.join(__dirname, '..');
const PUBLIC_DIR = path.join(ROOT, 'public');
const BUILD_DIR = path.join(ROOT, 'build');

/** Source-only files that must not ship to the CDN. */
const EXCLUDED_FROM_BUILD = new Set(['input.css', 'package.json']);

/** Generated by `npm run build:css`; the page is unstyled without it. */
const GENERATED_STYLESHEET = 'styles.css';

/**
 * Files that name a font. Anything in `public/fonts/` that none of them
 * mentions is an orphan and is left out of the build — `CorrectionBrush.otf`
 * sat in the deployment for months at 332 KB without a single reference.
 */
const FONT_REFERENCE_SOURCES = ['custom.css', 'index.html'];

/**
 * Cloudflare's `_headers` format: a path pattern, then indented header lines.
 *
 * @returns {string}
 */
function renderHeadersFile() {
  const lines = ['/*'];
  for (const [name, value] of Object.entries(staticSecurityHeaders())) {
    lines.push(`  ${name}: ${value}`);
  }

  // Both spellings: Cloudflare matches `_headers` rules against the request
  // path, and a visitor asks for `/`, never for `/index.html`. With only the
  // latter listed, the page guests actually load missed the no-cache rule.
  for (const route of ['/', '/index.html']) {
    lines.push('');
    lines.push(route);
    lines.push('  Cache-Control: no-cache');
  }

  // Font filenames are stable and their bytes never change in place; the
  // markup and CSS around them do.
  lines.push('');
  lines.push('/fonts/*');
  lines.push('  Cache-Control: public, max-age=31536000, immutable');

  lines.push('');
  return lines.join('\n');
}

/**
 * @returns {Set<string>} basenames of the fonts some source file references
 */
function referencedFonts() {
  const names = new Set();
  for (const source of FONT_REFERENCE_SOURCES) {
    const text = fs.readFileSync(path.join(PUBLIC_DIR, source), 'utf8');
    for (const match of text.matchAll(/[\w %.-]+\.(?:otf|ttf|woff2?)/gi)) {
      names.add(path.basename(match[0]));
    }
  }
  return names;
}

/**
 * @param {string} dir
 * @returns {{ entries: number, skippedFonts: string[] }}
 */
function copyPublicTree(dir) {
  const fonts = referencedFonts();
  const skippedFonts = [];

  fs.cpSync(PUBLIC_DIR, dir, {
    recursive: true,
    filter: (source) => {
      const name = path.basename(source);
      if (EXCLUDED_FROM_BUILD.has(name)) return false;
      if (path.dirname(source).endsWith('fonts') && !fonts.has(name)) {
        skippedFonts.push(name);
        return false;
      }
      return true;
    },
  });

  return {
    entries: fs.readdirSync(dir, { recursive: true }).length,
    skippedFonts,
  };
}

/**
 * The stylesheet is generated and gitignored, so a fresh clone that runs
 * `build:static` on its own would otherwise produce an unstyled site and say
 * nothing about it.
 */
function assertStylesheetBuilt() {
  if (!fs.existsSync(path.join(PUBLIC_DIR, GENERATED_STYLESHEET))) {
    throw new Error(
      `public/${GENERATED_STYLESHEET} is missing — run \`npm run build:css\` first ` +
        '(or `npm run build`, which does both).'
    );
  }
}

function build() {
  console.log('Building static site...');

  assertStylesheetBuilt();

  fs.rmSync(BUILD_DIR, { recursive: true, force: true });
  const { entries, skippedFonts } = copyPublicTree(BUILD_DIR);
  console.log(`  Copied ${entries} entries from public/`);
  for (const name of skippedFonts) {
    console.log(`  Skipped unreferenced font ${name}`);
  }

  const indexPath = path.join(BUILD_DIR, 'index.html');
  const template = fs.readFileSync(indexPath, 'utf8');
  fs.writeFileSync(indexPath, renderIndexHtml(template, content), 'utf8');
  console.log('  Rendered index.html');

  fs.writeFileSync(
    path.join(BUILD_DIR, 'config.json'),
    `${JSON.stringify(buildClientConfig(content), null, 2)}\n`,
    'utf8'
  );
  console.log('  Generated config.json');

  fs.writeFileSync(
    path.join(BUILD_DIR, '_headers'),
    renderHeadersFile(),
    'utf8'
  );
  console.log('  Generated _headers');

  console.log(`Build complete: ${path.relative(ROOT, BUILD_DIR)}/`);
}

if (require.main === module) {
  try {
    build();
  } catch (err) {
    console.error(`Build failed: ${err instanceof Error ? err.message : err}`);
    process.exit(1);
  }
}

module.exports = { build, renderHeadersFile, referencedFonts, BUILD_DIR };
