/**
 * Project directories, resolved once.
 *
 * `src/app.js`, `scripts/build-static.js` and two test suites each used to
 * recompute `path.join(__dirname, '..', 'public')` for themselves, while
 * `src/app.js` exported the value to nobody. Four copies of one fact is three
 * too many, and the exported copy was the one nothing imported.
 */

'use strict';

const path = require('node:path');

/** Repository root. */
const ROOT = path.join(__dirname, '..');

/** Everything served to a browser, and the source of the build tree. */
const PUBLIC_DIR = path.join(ROOT, 'public');

/** The deployable tree `scripts/build-static.js` writes. */
const BUILD_DIR = path.join(ROOT, 'build');

/** The template `src/render.js` substitutes into. */
const INDEX_TEMPLATE = path.join(PUBLIC_DIR, 'index.html');

/** Generated by `npm run build:css`; gitignored, so its absence is normal. */
const STYLESHEET = path.join(PUBLIC_DIR, 'styles.css');

module.exports = { ROOT, PUBLIC_DIR, BUILD_DIR, INDEX_TEMPLATE, STYLESHEET };
